### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by Cactusolo** [thej022214/hisse#16]
remotes::install_github("thej022214/hisse")
Error: Failed to install 'unknown package' from GitHub:
  SSL certificate problem: self signed certificate in certificate chain

#####################
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

**Comment by Caetanods** [comment]
Hello,
It is not clear what is the issue because the repository do exist. Please update your R and try again.
Note that the current R version is R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night" or above.
