### ISSUE TITLE
GeoHiSSE tutorial v1.9.10

### ISSUE THREAD

**Issue by azizka** [thej022214/hisse#18]
Hi, I am trying to follow the GeoHiSSE vignette. Two questions:

1) On page 4 in the second code chunk you set `phy$node.labels <- NULL`, however, phy does not have a slot "node labels" its rather "node.label". Is this on purpose?

2) The comment on Model 4 (code chunk 3, page 5) reads "GeoHiSSE model with 1 hidden trait, no range-dependent diversification", this is identical to Model 3. Yet, for model 4 you use `turnover <- c(1,2,3,4,5,6)` which seems to suggest range-dependent diversification. Am I missing something here?

**Comment by thej022214** [comment]
1) So, in the past, we've used diversitree to generate simulated trees, and for some reason the input tree having node labels like this can cause errors. I don't think this matters anymore, so it's not a necessary to include. I will remove.

2) It should be "GeoHiSSE model with 1 hidden trait" -- it definitely has range-dependent diversification. Good catch and I will change this.

**Comment by azizka** [comment]
thanks!
