### ISSUE TITLE
Understanding the data matrix for GeoHISSE 

### ISSUE THREAD

**Issue by dylanHco** [thej022214/hisse#21]
Hi Jeremy,

I am working on using GeoHISSE, but I am a little confused about how to score the areas matrix. I have reviewed both the 2018 paper and the recent updated tutorial, as well about the function in R. 

Sorry if this is redundant or if I misread this somewhere:

For GeoHISSE, it sounds like you need to score areas like: 0, 1, and 2. So for example if I wanted to compare lineages in the central Andes to lineages in southern Andes I would code it like this?

central Andes 0
southern Andes 1
widespread 01

Species A 0
Species B 01
Species C 1
Species D 1
etc

So I did this but got this error: 

`Error in GeoHiSSE(phy = phy2, data = data2, f = c(1, 1, 1), turnover = turnover, : states need to be one of 0, 1, or 2. See help
`
I am first confused about where the 2 would come in ?

I am also wondering if you can compare more than 2 areas? Sorry if I missed this somewhere, I am a newbie and still learning the software.

Many thanks,
Dylan

**Comment by thej022214** [comment]
So the data file should have two columns, where the first column has the species names and column 2 has area codes. Range information need to be 0, 1, or 2, where 0 is the widespread area "01", 1 is endemic area "00" and 2 is endemic area "11".

**Comment by dylanHco** [comment]
Thanks for the response. I just updated it, and now I get this error: 

`Initializing... 
Error in if (data[i] == 1) {: missing value where TRUE/FALSE needed
Traceback:

1. GeoHiSSE(phy = phy2, data = data2, f = c(1, 1, 1), turnover = turnover, 
 .     eps = eps, hidden.states = FALSE, trans.rate = trans.rate.mod, 
 .     turnover.upper = 100, trans.upper = 10)
2. OrganizeDataGeo(data = data.new[, 1], phy = phy, f = f, hidden.states = hidden.states)`

**Comment by thej022214** [comment]
You can send me your tree and data and the code you used so I can take a closer look. Not entirely sure what the issue is here. My guess is that it's treating something like a factor or something.

**Comment by dylanHco** [comment]
I do not think its the tree. I have run Misse with the tree, and the files are identical. 

I think it is something to do with the areas dataframe. The 0,1,2 in data frame are integers. Do they need to be something else? I tried to convert them with as.numeric, but that switched to double, and still got same error. 

Can I email you the csv file?

**Comment by thej022214** [comment]
Absolutely -- Send me the trait file, the tree, and the code you are using and I can take a look tonight (jmbeauli@uark.edu).
