### ISSUE TITLE
MiSSEGreedy error after finishing chunks, related to saving a file

### ISSUE THREAD

**Issue by jsoghigian** [thej022214/hisse#23]
Hi all, great work on HiSSE! 

I've just been trying to run through the MiSSE examples and I got an error midway through a run.  I get this error after the chunks have finished running for MiSSEGreedy for the eucalypts example:

> Error in gzfile(file, "wb") : cannot open the connection
> Calls: MiSSEGreedy -> save -> gzfile
> In addition: Warning message:
> In gzfile(file, "wb") :
>   cannot open compressed file '/home/john.soghigian/Downloads/final.combos.Rsave', probable reason 'No such file or directory'
> Execution halted

I'm running MiSSE on a cluster and I didn't specify that directory. I did follow the example code's suggestion and use a save file, but I expected that to be saved in my home directory (working directory), which has no Downloads directory. I think it is because the function MiSSEGreedy tries to save output in a particular directory (specified on line 444 here, https://github.com/thej022214/hisse/blob/master/R/misse.R), although I may be totally off there.

**Comment by thej022214** [comment]
I'll look into this now. Not sure based on your error message what the issue is. But I will get back to you shortly. Thanks for the heads up on this!

**Comment by jsoghigian** [comment]
Thanks Jeremy!
I probably should have provided more details... In case it is helpful, here's some more information on the run...
Here's the command I used, where most variables were set as in the example, save for cores (set to 40) and chunks (set to 40 to match the cores)

model.set_ml1 = MiSSEGreedy(phy=phy_ml1, # the phylogeny 
                        f=f, # sampling fraction
                        possible.combos=possibilities_ml1, # possible combinations of models
                        save.file=save.file_ml1, # the name of the file to save
                        stop.deltaAICc=stop.deltaAICc, # the deltaAIC to stop running
                        n.cores=n.cores, # number of cores
                        chunk.size=chunk.size) # size of the "chunk" of models

The error message occurred after (I think) MiSSEGreedy had finished working on the chunks. I've attached the stdout in case that helps facilitate figuring out what happened

[slurm-11725889.out.txt](https://github.com/thej022214/hisse/files/7529865/slurm-11725889.out.txt)

**Comment by thej022214** [comment]
Go ahead and try now. I think I figured out the issue. There was an errant debugging line left in the code. It's removed and I committed. I will wait until this all runs for you successfully before uploading onto CRAN.

**Comment by thej022214** [comment]
library(devtools)
devtools::install_github("thej022214/hisse")

(just in case)

**Comment by jsoghigian** [comment]
Great!  That did fix the error and the file is being properly written to the working directory now.  Thanks for the quick attention!
