### ISSUE TITLE
MuHiSSE error

### ISSUE THREAD

**Issue by animazum** [thej022214/hisse#26]
trying to run:

SupportRegionMuHiSSE(muhisse.obj= pigment_best_fit, n.points = 1000, 
                                         verbose = TRUE, min.number.points = 10, scale.int = 0.0001, desired.delta = 2)

after running  muhisse I get a model with all parameters but I get the next error. 

Error in OrganizeData(data = data, phy = phy, f = f, hidden.states = hidden.states,  : 
  argument "includes.fossils" is missing, with no default

the object pigment_best_fit has the argument includes fossils but apparently the function is not understanding it. 

Many thanks

**Comment by thej022214** [comment]
Forgot to commit on Friday. Should work now. Will wait a few days before I submit a new package version to CRAN.
