### ISSUE TITLE
Return averages from plotting

### ISSUE THREAD

**Issue by bomeara** [thej022214/hisse#3]
we want to model average. There are problems, though: 0A in one model might be 0B in another. Also, if we want to get average rate for 0*, it's not necessarily the straight mean of 0A and 0B rates -- what if 0B is far more common? We reconstruct rates on tree b/c the label drops out -- we just average rates within a model and then weighted average (Akaike) across models. So we have a diversification rate on each edge. Get weighted average of these (weighting by brlen) to get the overall average rates. Can include CID models in this average. 

Disadvantage is that the reconstruction is slow.

**Comment by bomeara** [comment]
Could also do just across the tips -- still requires recon at tips

**Comment by thej022214** [comment]
Added function that provides rates for nodes and tips, or just tips, or just nodes.
